### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Daggerbot** [Daggerbot/mm_video#3]
X11
- [ ] Font loading and text rendering
- [ ] Pixmap creation and rendering
- [ ] Full screen support

Windows
- [ ] Graphics context
- [ ] OpenGL
- [ ] Font loading and text rendering
- [ ] Pixmap creation and rendering
- [ ] Full screen support
